name: Deploy (staging) PR branch
on:
  issue_comment:
    types: [created]

jobs:
  trigger-pr-branch-deploy:
    runs-on: ubuntu-22.04
    permissions:
      actions: write
    if: >
      github.event.issue.pull_request &&
      github.event.issue.state == 'open' &&
      github.event.comment.body == '/deploy'
    steps:
      - name: Get pull request HEAD ref
        id: get-ref
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const response = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
            console.log(response.data)
            return response.data.head.ref
      - name: Trigger branch deploy
        uses: actions/github-script@v7
        with:
          script: |
            const response = await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "deploy.yaml",
              ref: "${{steps.get-ref.outputs.result}}",
              inputs: {
                "aws-eb-env": `${vars.AWS_EB_APP_NAME}-pr-${context.issue.number}`,
                "github-env": "staging",
                "pull-request-ref": `${context.issue.number}`
              }
            })
            console.log(response)
